kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 80
  - containerPort: 30002
    hostPort: 8080
  - containerPort: 30003
    hostPort: 443  
    listenAddress: "0.0.0.0" 
    protocol: udp 
- role: worker
- role: worker