apiVersion: v1
kind: Service
metadata:
  name: codeserver
  labels:
    env: dev
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30001  
      port: 80         
      targetPort: 80   
    - name: code
      nodePort: 30002  
      port: 8080       
      targetPort: 8080
  selector: 
    env: dev